# pong-provider Makefile

CAPABILITY_ID = "wasmcloud:examples:pong"
NAME = "pong-provider"
VENDOR = "Adobe"
PROJECT = pong_provider
VERSION = 0.1.0
REVISION = 0

include ./provider.mk

test::
	cargo clippy --all-targets --all-features

